name: Deploy Etalon Server Locally

on:
  push:
    branches:
      - main

runs-on: ubuntu-latest # Теперь эта метка будет запускать контейнер node:16-bullseye

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Этот шаг нужен, чтобы Docker CLI был доступен внутри контейнера node
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.4'
        
      - name: Build and Push to Local Registry
        run: |
          # Теперь мы можем обращаться к registry по имени сервиса,
          # так как контейнер задачи находится в той же сети.
          REGISTRY_HOST=registry:5000 
          IMAGE_NAME=$REGISTRY_HOST/serty/etalon-server:latest
        
                   
          # Сборка образа
          docker build -t $IMAGE_NAME .
          
          # Пуш в локальный registry
          docker push $IMAGE_NAME

      - name: Deploy to Production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Здесь мы используем IP-адрес или домен хоста, т.к. команда выполняется
            # снаружи docker-compose сети. Замените на IP вашего хоста.
            REGISTRY_HOST=localhost:5000 
            IMAGE_NAME=$REGISTRY_HOST/serty/etalon-server:latest

            # ... остальная часть скрипта без изменений ...
            APP_DIR="/opt/etalon-server"
            mkdir -p $APP_DIR/logs $APP_DIR/ftp_cache
            echo "${{ secrets.ENV_FILE_CONTENT }}" | base64 -d > $APP_DIR/.env
            docker stop etalon-server || true
            docker rm etalon-server || true
            docker pull $IMAGE_NAME
            docker run -d --name etalon-server --restart unless-stopped -p 8080:8080 -v $APP_DIR/logs:/root/logs -v $APP_DIR/ftp_cache:/root/ftp_cache --env-file $APP_DIR/.env $IMAGE_NAME