name: Deploy Etalon Server

# Триггер: запускать workflow при пуше в ветку 'main'
on:
  push:
    branches:
      - main

runs-on: ubuntu-latest

jobs:
  build-and-deploy:
    # Запускать на последней версии Ubuntu, предоставляемой ранером
    runs-on: ubuntu-latest
    steps:
      # Шаг 1: Получение исходного кода из репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Настройка окружения Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.4'


      # Этап сборки и пуша в локальный registry
      - name: Build and Push to Local Registry
        run: |
          # IP-адрес хоста, где запущен docker-compose и registry
          # Либо localhost, если ранер на той же машине
          REGISTRY_HOST=localhost:5000
          IMAGE_NAME=$REGISTRY_HOST/serty/etalon-server:latest
          
          # Сборка образа
          docker build -t $IMAGE_NAME .
          
          # Пуш в локальный registry
          docker push $IMAGE_NAME

      # Шаг 6: Развертывание на продакшен-сервере по SSH
      - name: Deploy to Production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # IP-адрес хоста, где запущен docker-compose и registry
            REGISTRY_HOST=localhost:5000
            IMAGE_NAME=$REGISTRY_HOST/serty/etalon-server:latest

            # Путь к директории приложения на продакшен-сервере
            APP_DIR="/opt/etalon-server"
            mkdir -p $APP_DIR/logs
            mkdir -p $APP_DIR/ftp_cache

            # Создаем .env файл
            echo "${{ secrets.ENV_FILE_CONTENT }}" | base64 -d > $APP_DIR/.env

            # Останавливаем и удаляем старый контейнер
            docker stop etalon-server || true
            docker rm etalon-server || true

            # Скачиваем свежий образ ИЗ ЛОКАЛЬНОГО REGISTRY
            docker pull $IMAGE_NAME

            # Запускаем новый контейнер
            docker run -d \
              --name etalon-server \
              --restart unless-stopped \
              -p 8080:8080 \
              -v $APP_DIR/logs:/root/logs \
              -v $APP_DIR/ftp_cache:/root/ftp_cache \
              --env-file $APP_DIR/.env \
              $IMAGE_NAME