
name: etalon
services:
  # 1. База данных
  db:
    image: postgres:16-alpine
    container_name: db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - etalon-net

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - etalon-net

  # # 2. Инициализатор (Сидер)
  # init-seeder:
  #   container_name: seeder
  #   build:
  #     context: ..
  #     dockerfile: docker/Dockerfile
  #   env_file:
  #     - .env
  #   command: ["./etalon-server", "--seed"]
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   networks:
  #     - etalon-net

  # 3. Основной сервер
  server:
    container_name: server
    build:
      context: ..
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "9999:8080"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      # init-seeder:
      #   condition: service_completed_successfully
    volumes:
      # Монтируем папку из корня проекта внутрь контейнера
      - ${HOST_PROJECT_PATH}/ftp_cache:/app/ftp_cache
    networks:
      - etalon-net

  # 4. Фронт
  frontend:
    container_name: frontend
    build:
      # Путь относительно docker-compose.yml к папке фронта
      context: ../front-ui 
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      # Маппим 5173 хоста на 80 порт Nginx внутри
      - "80:80"
    depends_on:
      - server
    networks:
      - etalon-net

volumes:
  redis_data:

networks:
  etalon-net:
    driver: bridge
